baseURL: "https://kasegao.github.io/"
canonifyurls: false
publishDir: "public"
title: "Webgao"
paginate: 10
theme: "PaperMod"

enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguage: ja
languages:
  ja:
    languageName: "日本語"
    weight: 1
    menu:
      main:
        - identifier: posts
          name: 投稿
          url: posts
          weight: 5
        - identifier: profile
          name: プロフィール
          url: fixed/profile
          weight: 10
        - identifier: works
          name: 業績
          url: fixed/works
          weight: 15
        - identifier: categories
          name: カテゴリ
          url: categories/
          weight: 20
        - identifier: tags
          name: タグ
          url: tags/
          weight: 25
  en:
    languageName: English
    weight: 2
    menu:
      main:
        - identifier: posts
          name: posts
          url: posts
          weight: 5
        - identifier: profile
          name: profile
          url: fixed/profile
          weight: 10
        - identifier: works
          name: works
          url: fixed/works
          weight: 15
        - identifier: categories
          name: categories
          url: categories/
          weight: 20
        - identifier: tags
          name: tags
          url: tags/
          weight: 25

params:
  env: production
  googleAnalyticsID: G-6S54ZMMLWL
  amazonJpAffiliateID: "kasega0-22"
  title: "webgao"
  description: "kasegao's website"
  keywords: [Kasega0, kasegao, webgao, かせがお, ウェブがお]
  author: ["kasegao"]
  # author: ["Me", "You"] # multiple authors
  images: ["profile.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"
    safari_pinned_tab: "favicon/safari-pinned-tab.svg"

  label:
    text: "🏠 Home"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "kasegao"
    subtitle: "a [researcher](https://orcid.org/0000-0002-7950-0248) & engineer."
    imageUrl: "profile.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image

  socialIcons:
    - name: twitter
      url: "https://twitter.com/Kasega0"
    - name: github
      url: "https://github.com/kasegao"
    - name: zenn
      url: "https://zenn.dev/kasega0"
    - name: email
      url: "mailto:shimomura@hapis.k.u-tokyo.ac.jp"
    - name: orcid
      url: "https://orcid.org/0000-0002-7950-0248"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/kasegao/kasegao.github.io/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
